### ISSUE TITLE
Use GitHub API v4

### ISSUE THREAD

**Issue by quantumpacket** [Ullaakut/astronomer#4]
The v4 API is GraphQL based. So it will drastically cut down on the number of requests needed.

https://developer.github.com/v4/

**Comment by Ullaakut** [comment]
I looked into it and unfortunately there is a slight issue.

The current way user info and contributions are fetched is that for each user we make one query to get their profile data, and one query to get their user contributions.

Using the GRPC API, I can get multiple user information responses within the same query, but I can only get their contributions year by year, which means that for example if I want to get the contributions of a group of users up to 10 years in the past, I'll need to query all of those users again 10 times.

Also, the rate limiting works differently on the GraphQL and calculates costs in terms of how many nodes are queried at the same time, which turns out to still be advantageous compared to the v3 API. For example, getting one year of 30 users' contributions costs only 1 point out of 5000 hourly points.

Overall I think it's worth it to use GraphQL to fetch the data, but it will require quite some logic in order to get lifetime contribution statistics effectively.

**Comment by Ullaakut** [comment]
In progress on branch [`use-github-apiv4`](https://github.com/Ullaakut/astronomer/tree/use-github-apiv4).

It's already working pretty well, and comes with a few other advantages:

* Caching is now progressive instead of done all at once at the end of the scan
	* This means that you can stop a scan and continue where you left it later on
* Scans are much faster
	* About 200% faster for small repositories
	* About 4500% for medium and big repositories ([`ullaakut/cameradar`](https://github.com/ullaakut/cameradar) took a bit over 2hrs to scan before and it now takes 2mn50s now.
* We now have more precise data over the contributions, which allowed me to change the way trust is computed to give less weight to private contributions (which can more easily be faked/hidden) and more to public contributions depending on their types.

I just have a few more improvements to make but I think the new and improved Astronomer will be available this morning! Thanks to you @quantumpacket :)
